package CC.Encycloped.Abs.Org.Comput.Bi;

import CC.$.Q2$2.Bool2$2;

public class Tabl_$MOr1
{
	public static void AB(boolean[] Rsult,boolean A,boolean B)
	{
		Rsult[0]=A;
		Rsult[1]=B;
	}
	public static final Bool2$2
		AnilAtn=(A,B,Rsult)->
		{
			boolean Both=A&B;

			AB(Rsult,
				A^Both,
				B^Both);
		};
	public static final boolean Q=false;
	public static final Bool2$2
		OO_OO_OO_OO=(A,B,Rsult)->{AB(Rsult,false,false);},IO_OO_OO_OO=(A,B,Rsult)->{return !(A|B);},OI_OO_OO_OO=(A,B,Rsult)->{return A&!B;},II_OO_OO_OO=(A,B,Rsult)->{return Q;},				OO_IO_OO_OO=(A,B,Rsult)->{return (!A)&B;},IO_IO_OO_OO=(A,B,Rsult)->{return Q;},OI_IO_OO_OO=(A,B,Rsult)->{return (!Rsult)&(A^B);},II_IO_OO_OO=(A,B,Rsult)->{return Q;},				OO_OI_OO_OO=(A,B,Rsult)->{return A&B;},IO_OI_OO_OO=(A,B,Rsult)->{return (!Rsult)&(A==B);},OI_OI_OO_OO=(A,B,Rsult)->{return A&(!Rsult);},II_OI_OO_OO=(A,B,Rsult)->{return (A|(!B))&!Rsult;},				OO_II_OO_OO=(A,B,Rsult)->{return B&(!Rsult);},IO_II_OO_OO=(A,B,Rsult)->{return ((!A)|B)&(!Rsult);},OI_II_OO_OO=(A,B,Rsult)->{return (A|B)&(!Rsult);},II_II_OO_OO=(A,B,Rsult)->{return !Rsult;},
		OO_OO_IO_OO=(A,B,Rsult)->{return Q;},IO_OO_IO_OO=(A,B,Rsult)->{return Q;},OI_OO_IO_OO=(A,B,Rsult)->{return Q;},II_OO_IO_OO=(A,B,Rsult)->{return Q;},				OO_IO_IO_OO=(A,B,Rsult)->{return Q;},IO_IO_IO_OO=(A,B,Rsult)->{return Q;},OI_IO_IO_OO=(A,B,Rsult)->{return Q;},II_IO_IO_OO=(A,B,Rsult)->{return Q;},				OO_OI_IO_OO=(A,B,Rsult)->{return Q;},IO_OI_IO_OO=(A,B,Rsult)->{return Q;},OI_OI_IO_OO=(A,B,Rsult)->{return Q;},II_OI_IO_OO=(A,B,Rsult)->{return Q;},													OO_II_IO_OO=(A,B,Rsult)->{return Q;},IO_II_IO_OO=(A,B,Rsult)->{return Q;},OI_II_IO_OO=(A,B,Rsult)->{return Q;},II_II_IO_OO=(A,B,Rsult)->{return Q;},
		OO_OO_OI_OO=(A,B,Rsult)->{return Q;},IO_OO_OI_OO=(A,B,Rsult)->{return Q;},OI_OO_OI_OO=(A,B,Rsult)->{return Q;},II_OO_OI_OO=(A,B,Rsult)->{return Q;},				OO_IO_OI_OO=AnilAtn,IO_IO_OI_OO=(A,B,Rsult)->{return Q;},OI_IO_OI_OO=(A,B,Rsult)->{return Q;},II_IO_OI_OO=(A,B,Rsult)->{return Q;},											OO_OI_OI_OO=(A,B,Rsult)->{return Q;},IO_OI_OI_OO=(A,B,Rsult)->{return Q;},OI_OI_OI_OO=(A,B,Rsult)->{return Q;},II_OI_OI_OO=(A,B,Rsult)->{return Q;},				OO_II_OI_OO=(A,B,Rsult)->{return Q;},IO_II_OI_OO=(A,B,Rsult)->{return Q;},OI_II_OI_OO=(A,B,Rsult)->{return Q;},II_II_OI_OO=(A,B,Rsult)->{return Q;},
		OO_OO_II_OO=(A,B,Rsult)->{return Q;},IO_OO_II_OO=(A,B,Rsult)->{return Q;},OI_OO_II_OO=(A,B,Rsult)->{return Q;},II_OO_II_OO=(A,B,Rsult)->{return Q;},				OO_IO_II_OO=(A,B,Rsult)->{return Q;},IO_IO_II_OO=(A,B,Rsult)->{return Q;},OI_IO_II_OO=(A,B,Rsult)->{return Q;},II_IO_II_OO=(A,B,Rsult)->{return Q;},													OO_OI_II_OO=(A,B,Rsult)->{return Q;},IO_OI_II_OO=(A,B,Rsult)->{return Q;},OI_OI_II_OO=(A,B,Rsult)->{return Q;},II_OI_II_OO=(A,B,Rsult)->{return Q;},													OO_II_II_OO=(A,B,Rsult)->{return Q;},IO_II_II_OO=(A,B,Rsult)->{return Q;},OI_II_II_OO=(A,B,Rsult)->{return Q;},II_II_II_OO=(A,B,Rsult)->{return Q;},

		OO_OO_OO_IO=(A,B,Rsult)->{return Q;},IO_OO_OO_IO=(A,B,Rsult)->{return Q;},OI_OO_OO_IO=(A,B,Rsult)->{return Q;},II_OO_OO_IO=(A,B,Rsult)->{return Q;},				OO_IO_OO_IO=(A,B,Rsult)->{return Q;},IO_IO_OO_IO=(A,B,Rsult)->{return Q;},OI_IO_OO_IO=(A,B,Rsult)->{return Q;},II_IO_OO_IO=(A,B,Rsult)->{return Q;},											OO_OI_OO_IO=(A,B,Rsult)->{return Q;},IO_OI_OO_IO=(A,B,Rsult)->{return Q;},OI_OI_OO_IO=(A,B,Rsult)->{return Q;},II_OI_OO_IO=(A,B,Rsult)->{return Q;},				OO_II_OO_IO=(A,B,Rsult)->{return Q;},IO_II_OO_IO=(A,B,Rsult)->{return Q;},OI_II_OO_IO=(A,B,Rsult)->{return Q;},II_II_OO_IO=(A,B,Rsult)->{return Q;},
		OO_OO_IO_IO=(A,B,Rsult)->{return Q;},IO_OO_IO_IO=(A,B,Rsult)->{return Q;},OI_OO_IO_IO=(A,B,Rsult)->{return Q;},II_OO_IO_IO=(A,B,Rsult)->{return Q;},											OO_IO_IO_IO=(A,B,Rsult)->{return Q;},IO_IO_IO_IO=(A,B,Rsult)->{return Q;},OI_IO_IO_IO=(A,B,Rsult)->{return Q;},II_IO_IO_IO=(A,B,Rsult)->{return Q;},				OO_OI_IO_IO=(A,B,Rsult)->{return Q;},IO_OI_IO_IO=(A,B,Rsult)->{return Q;},OI_OI_IO_IO=(A,B,Rsult)->{return Q;},II_OI_IO_IO=(A,B,Rsult)->{return Q;},				OO_II_IO_IO=(A,B,Rsult)->{return Q;},IO_II_IO_IO=(A,B,Rsult)->{return Q;},OI_II_IO_IO=(A,B,Rsult)->{return Q;},II_II_IO_IO=(A,B,Rsult)->{return Q;},
		OO_OO_OI_IO=(A,B,Rsult)->{return Q;},IO_OO_OI_IO=(A,B,Rsult)->{return Q;},OI_OO_OI_IO=(A,B,Rsult)->{return Q;},II_OO_OI_IO=(A,B,Rsult)->{return Q;},				OO_IO_OI_IO=(A,B,Rsult)->{return Q;},IO_IO_OI_IO=(A,B,Rsult)->{return Q;},OI_IO_OI_IO=(A,B,Rsult)->{return Q;},II_IO_OI_IO=(A,B,Rsult)->{return Q;},				OO_OI_OI_IO=(A,B,Rsult)->{return Q;},IO_OI_OI_IO=(A,B,Rsult)->{return Q;},OI_OI_OI_IO=(A,B,Rsult)->{return Q;},II_OI_OI_IO=(A,B,Rsult)->{return Q;},				OO_II_OI_IO=(A,B,Rsult)->{return Q;},IO_II_OI_IO=(A,B,Rsult)->{return Q;},OI_II_OI_IO=(A,B,Rsult)->{return Q;},II_II_OI_IO=(A,B,Rsult)->{return Q;},
		OO_OO_II_IO=(A,B,Rsult)->{return Q;},IO_OO_II_IO=(A,B,Rsult)->{return Q;},OI_OO_II_IO=(A,B,Rsult)->{return Q;},II_OO_II_IO=(A,B,Rsult)->{return Q;},												OO_IO_II_IO=(A,B,Rsult)->{return Q;},IO_IO_II_IO=(A,B,Rsult)->{return Q;},OI_IO_II_IO=(A,B,Rsult)->{return Q;},II_IO_II_IO=(A,B,Rsult)->{return Q;},												OO_OI_II_IO=(A,B,Rsult)->{return Q;},IO_OI_II_IO=(A,B,Rsult)->{return Q;},OI_OI_II_IO=(A,B,Rsult)->{return Q;},II_OI_II_IO=(A,B,Rsult)->{return Q;},				OO_II_II_IO=(A,B,Rsult)->{return Q;},IO_II_II_IO=(A,B,Rsult)->{return Q;},OI_II_II_IO=(A,B,Rsult)->{return Q;},II_II_II_IO=(A,B,Rsult)->{return Q;},

		OO_OO_OO_OI=(A,B,Rsult)->{return Q;},IO_OO_OO_OI=(A,B,Rsult)->{return Q;},OI_OO_OO_OI=(A,B,Rsult)->{return Q;},II_OO_OO_OI=(A,B,Rsult)->{return Q;},				OO_IO_OO_OI=(A,B,Rsult)->{return Q;},IO_IO_OO_OI=(A,B,Rsult)->{return Q;},OI_IO_OO_OI=(A,B,Rsult)->{return Q;},II_IO_OO_OI=(A,B,Rsult)->{return Q;},				OO_OI_OO_OI=(A,B,Rsult)->{return Q;},IO_OI_OO_OI=(A,B,Rsult)->{return Q;},OI_OI_OO_OI=(A,B,Rsult)->{return Q;},II_OI_OO_OI=(A,B,Rsult)->{return Q;},												OO_II_OO_OI=(A,B,Rsult)->{return Q;},IO_II_OO_OI=(A,B,Rsult)->{return Q;},OI_II_OO_OI=(A,B,Rsult)->{return Q;},II_II_OO_OI=(A,B,Rsult)->{return Q;},
		OO_OO_IO_OI=(A,B,Rsult)->{return Q;},IO_OO_IO_OI=(A,B,Rsult)->{return Q;},OI_OO_IO_OI=(A,B,Rsult)->{return Q;},II_OO_IO_OI=(A,B,Rsult)->{return Q;},				OO_IO_IO_OI=(A,B,Rsult)->{return Q;},IO_IO_IO_OI=(A,B,Rsult)->{return Q;},OI_IO_IO_OI=(A,B,Rsult)->{return Q;},II_IO_IO_OI=(A,B,Rsult)->{return Q;},				OO_OI_IO_OI=(A,B,Rsult)->{return Q;},IO_OI_IO_OI=(A,B,Rsult)->{return Q;},OI_OI_IO_OI=(A,B,Rsult)->{return Q;},II_OI_IO_OI=(A,B,Rsult)->{return Q;},				OO_II_IO_OI=(A,B,Rsult)->{return Q;},IO_II_IO_OI=(A,B,Rsult)->{return Q;},OI_II_IO_OI=(A,B,Rsult)->{return Q;},II_II_IO_OI=(A,B,Rsult)->{return Q;},
		OO_OO_OI_OI=(A,B,Rsult)->{return Q;},IO_OO_OI_OI=(A,B,Rsult)->{return Q;},OI_OO_OI_OI=(A,B,Rsult)->{return Q;},II_OO_OI_OI=(A,B,Rsult)->{return Q;},												OO_IO_OI_OI=(A,B,Rsult)->{return Q;},IO_IO_OI_OI=(A,B,Rsult)->{return Q;},OI_IO_OI_OI=(A,B,Rsult)->{return Q;},II_IO_OI_OI=(A,B,Rsult)->{return Q;},				OO_OI_OI_OI=(A,B,Rsult)->{return Q;},IO_OI_OI_OI=(A,B,Rsult)->{return Q;},OI_OI_OI_OI=(A,B,Rsult)->{return Q;},II_OI_OI_OI=(A,B,Rsult)->{return Q;},				OO_II_OI_OI=(A,B,Rsult)->{return Q;},IO_II_OI_OI=(A,B,Rsult)->{return Q;},OI_II_OI_OI=(A,B,Rsult)->{return Q;},II_II_OI_OI=(A,B,Rsult)->{return Q;},
		OO_OO_II_OI=(A,B,Rsult)->{return Q;},IO_OO_II_OI=(A,B,Rsult)->{return Q;},OI_OO_II_OI=(A,B,Rsult)->{return Q;},II_OO_II_OI=(A,B,Rsult)->{return Q;},													OO_IO_II_OI=(A,B,Rsult)->{return Q;},IO_IO_II_OI=(A,B,Rsult)->{return Q;},OI_IO_II_OI=(A,B,Rsult)->{return Q;},II_IO_II_OI=(A,B,Rsult)->{return Q;},				OO_OI_II_OI=(A,B,Rsult)->{return Q;},IO_OI_II_OI=(A,B,Rsult)->{return Q;},OI_OI_II_OI=(A,B,Rsult)->{return Q;},II_OI_II_OI=(A,B,Rsult)->{return Q;},												OO_II_II_OI=(A,B,Rsult)->{return Q;},IO_II_II_OI=(A,B,Rsult)->{return Q;},OI_II_II_OI=(A,B,Rsult)->{return Q;},II_II_II_OI=(A,B,Rsult)->{return Q;},

		OO_OO_OO_II=(A,B,Rsult)->{return Q;},IO_OO_OO_II=(A,B,Rsult)->{return Q;},OI_OO_OO_II=(A,B,Rsult)->{return Q;},II_OO_OO_II=(A,B,Rsult)->{return Q;},				OO_IO_OO_II=(A,B,Rsult)->{return Q;},IO_IO_OO_II=(A,B,Rsult)->{return Q;},OI_IO_OO_II=(A,B,Rsult)->{return Q;},II_IO_OO_II=(A,B,Rsult)->{return Q;},													OO_OI_OO_II=(A,B,Rsult)->{return Q;},IO_OI_OO_II=(A,B,Rsult)->{return Q;},OI_OI_OO_II=(A,B,Rsult)->{return Q;},II_OI_OO_II=(A,B,Rsult)->{return Q;},														OO_II_OO_II=(A,B,Rsult)->{return Q;},IO_II_OO_II=(A,B,Rsult)->{return Q;},OI_II_OO_II=(A,B,Rsult)->{return Q;},II_II_OO_II=(A,B,Rsult)->{return Q;},
		OO_OO_IO_II=(A,B,Rsult)->{return Q;},IO_OO_IO_II=(A,B,Rsult)->{return Q;},OI_OO_IO_II=(A,B,Rsult)->{return Q;},II_OO_IO_II=(A,B,Rsult)->{return Q;},													OO_IO_IO_II=(A,B,Rsult)->{return Q;},IO_IO_IO_II=(A,B,Rsult)->{return Q;},OI_IO_IO_II=(A,B,Rsult)->{return Q;},II_IO_IO_II=(A,B,Rsult)->{return Q;},				OO_OI_IO_II=(A,B,Rsult)->{return Q;},IO_OI_IO_II=(A,B,Rsult)->{return Q;},OI_OI_IO_II=(A,B,Rsult)->{return Q;},II_OI_IO_II=(A,B,Rsult)->{return Q;},												OO_II_IO_II=(A,B,Rsult)->{return Q;},IO_II_IO_II=(A,B,Rsult)->{return Q;},OI_II_IO_II=(A,B,Rsult)->{return Q;},II_II_IO_II=(A,B,Rsult)->{return Q;},
		OO_OO_OI_II=(A,B,Rsult)->{return Q;},IO_OO_OI_II=(A,B,Rsult)->{return Q;},OI_OO_OI_II=(A,B,Rsult)->{return Q;},II_OO_OI_II=(A,B,Rsult)->{return Q;},														OO_IO_OI_II=(A,B,Rsult)->{return Q;},IO_IO_OI_II=(A,B,Rsult)->{return Q;},OI_IO_OI_II=(A,B,Rsult)->{return Q;},II_IO_OI_II=(A,B,Rsult)->{return Q;},														OO_OI_OI_II=(A,B,Rsult)->{return Q;},IO_OI_OI_II=(A,B,Rsult)->{return Q;},OI_OI_OI_II=(A,B,Rsult)->{return Q;},II_OI_OI_II=(A,B,Rsult)->{return Q;},				OO_II_OI_II=(A,B,Rsult)->{return Q;},IO_II_OI_II=(A,B,Rsult)->{return Q;},OI_II_OI_II=(A,B,Rsult)->{return Q;},II_II_OI_II=(A,B,Rsult)->{return Q;},
		OO_OO_II_II=(A,B,Rsult)->{return Rsult;},IO_OO_II_II=(A,B,Rsult)->{return Q;},OI_OO_II_II=(A,B,Rsult)->{return Q;},II_OO_II_II=(A,B,Rsult)->{return Q;},				OO_IO_II_II=(A,B,Rsult)->{return Q;},IO_IO_II_II=(A,B,Rsult)->{return Q;},OI_IO_II_II=(A,B,Rsult)->{return Q;},II_IO_II_II=(A,B,Rsult)->{return Q;},				OO_OI_II_II=(A,B,Rsult)->{return Q;},IO_OI_II_II=(A,B,Rsult)->{return Q;},OI_OI_II_II=(A,B,Rsult)->{return Q;},II_OI_II_II=(A,B,Rsult)->{return Q;},				OO_II_II_II=(A,B,Rsult)->{return Q;},IO_II_II_II=(A,B,Rsult)->{return Q;},OI_II_II_II=(A,B,Rsult)->{return Q;},II_II_II_II=(A,B,Rsult)->{return Q;};
}